### ISSUE TITLE
Integration tests idea

### ISSUE THREAD

**Issue by zsluedem** [Vid201/aa-bundler#1]
# Problem

We need a local Ethereum network tool like Hardhat tests. They should provide enough ~~gRPC~~JSON endpoint and correct EVM execution. The bundler could be able to integrate with the local test network.

# Proposed solution

I suggest we used the [anvil tool](https://github.com/foundry-rs/foundry/tree/master/anvil). It is written in Rust and it is light enough for tests.

@Vid201 Please let me know if you have some other options to choose.

# Goal

1. Introduce anvil tool into the repo.
2. Setup the test environment for [abstract contracts](https://github.com/eth-infinitism/account-abstraction/tree/develop/contracts/core) .
3. Integrate with the anvil node with bundler.(This could be another issue.)

The goal here is to achieve 1 and 2.

**Comment by Vid201** [comment]
That's a great issue!

Hmmm, it's an option to use anvil. Corrent me if I'm wrong, but both hardhat and anvil do not support gRPC endpoints.

But I think it's fine to start with JSON RPC calls to either hardhat or anvil (we can reuse/start hardhat setup from [here](https://github.com/eth-infinitism/bundler), no need to add the setup here at the beginning) with [ethers-rs](https://github.com/gakonst/ethers-rs). This way, we do not have to worry about the wallet side and smart contracts (and deploying them). gRPC would come into play when bundler is integrated into the execution client and would have direct access to the blockchain state and EVM.

Similar to how [stackup-bundler](https://github.com/stackup-wallet/stackup-bundler/blob/b4bce053bd9ed90ee449f6b320a3ee7a4b4e05f3/internal/start/private.go) connect to Ethereum node with ethclient (geth).

At later stages we could develop some client SDK and tests for client side also.

What do you think? @zsluedem

**Comment by zsluedem** [comment]
https://github.com/Vid201/aa-bundler/pull/26 closing this now because anvil is successfully landed
