### ISSUE TITLE
Integration into Rust execution client

### ISSUE THREAD

**Issue by Vid201** [Vid201/aa-bundler#15]

**Comment by zsluedem** [comment]
I did some investigation these days and found that currently the [RETH](https://github.com/paradigmxyz/reth) is still in the early stage and the normal execution client functions are not available and [Akula](https://github.com/akula-bft/akula) is archived.

**Comment by Vid201** [comment]
Hi @zsluedem. Yes, I saw that Akula is archived/not in development when the Reth came out (which is, in fact, based on Erigon and Akula architecture). I am not entirely sure what you mean by "the normal execution client functions"?

**Comment by zsluedem** [comment]
Currently, reth doesn't need a consensus client to  interact with which means reth could not sync with the network and you have to input the blockhash you want to sync with. 
And the [standard execution api](https://github.com/paradigmxyz/reth/issues/616) is not implemented yet.

I just want to comment on the current status of these rust execution clients. reth is under development and we should definitely revisit it later.

**Comment by Vid201** [comment]
> Currently, reth doesn't need a consensus client to interact with which means reth could not sync with the network and you have to input the blockhash you want to sync with. And the [standard execution api](https://github.com/paradigmxyz/reth/issues/616) is not implemented yet.
> 
> I just want to comment on the current status of these rust execution clients. reth is under development and we should definitely revisit it later.

Ok, I got it.

I agree; it would make sense to revisit this sometime in the future and create a list of all the features missing in Reth that are needed.

**Comment by gakonst** [comment]
Would love to understand which features you need either to use reth as a node, or components of it as a library

**Comment by Vid201** [comment]
> Would love to understand which features you need either to use reth as a node, or components of it as a library

@gakonst Most likely both. In the short term, the bundler will be run as a standalone component connecting to the execution client over API (which can work with any execution client, though with some constraints). In the long term, we are exploring making bundling capabilities as part of the Ethereum node.

**Short-term:** run alongside the execution client node, with communication happening over RPC API (or GRPC). The execution client node must support standard API endpoints (such as `eth_sendRawTransaction` for submitting bundles) and additional tracing API (at the moment, only supported by geth and Erigon AFAIK).

**Long-term:** integration into reth would be interesting. Starting reth with some flag parameter (--bundling) would enable bundling to run alongside standard functionalities. In this case, it would make sense to reuse some components (like database and low-level primitives) or extend some other things (RPC endpoints). Some components (db) can also be used in the short term (if it makes sense) to make long-term goals easier to achieve.
