### ISSUE TITLE
Introduce github action cache to improve ci 

### ISSUE THREAD

**Issue by zsluedem** [Vid201/aa-bundler#37]
Currently the ci is running so slow. It took about 17 mins to complete the ci.

We could accelerate it by introducing the github cache which could save a lot of time on network downloading.

Some guides: 
1. https://github.com/actions/cache
2. https://github.com/marketplace/actions/rust-cache
3. https://github.com/marketplace/actions/yarn-install-cache

**Comment by Vid201** [comment]
Sounds good
