### ISSUE TITLE
Provide a debug api flag for bundler api

### ISSUE THREAD

**Issue by zsluedem** [Vid201/aa-bundler#72]
I want to continue the question https://github.com/Vid201/aa-bundler/pull/43#discussion_r1092723766 here.

Currently, our debug API is config with a compiling flag [#[cfg(debug_assertions)]](https://github.com/Vid201/aa-bundler/blob/cc031b76bf05c32bc024346a38a3c55b565e9631/bin/bundler-rpc.rs#L41) which means the debug api would be there only when we build with `cargo build`. If we want to build with release version `cargo build --release` with compiler optimization, there are no debug apis.

I suggest we using the method like geth does providing a flag like `--api debug` to enable debug api instead of put it as a compilation flag. In that way, we could use release version to run tests especially for https://bundler-test-results.eip4337.com/. (BTW, @Vid201 very great job on it.) I want to see whether we could beat stackup-bundler on performance.

@Vid201 What do you think?

**Comment by Vid201** [comment]
Agree 100 % percent.

After some testing and thinking about that, I agree it's better to add additional flag like geth to enable certain API endpoints.

**Comment by Vid201** [comment]
And we can provide two packages on the repo - one with enabled debug api (for testing) and one without.
