### ISSUE TITLE
DB user operation pool

### ISSUE THREAD

**Issue by Vid201** [Vid201/aa-bundler#8]
Use [mdbx](https://docs.rs/libmdbx/latest/libmdbx/).

**Comment by zsluedem** [comment]
@Vid201 Hello Vid. I am just curious about why you chose mdbx here? Is it because akula is using it?
Did you consider some other options like https://docs.rs/lmdb/latest/lmdb/, https://docs.rs/rocksdb/latest/rocksdb/ or https://docs.rs/leveldb/latest/leveldb/ ?
And Reth is using its own wrapper https://github.com/paradigmxyz/reth/tree/main/crates/storage/libmdbx-rs with more free liscense.

**Comment by Vid201** [comment]
> @Vid201 Hello Vid. I am just curious about why you chose mdbx here? Is it because akula is using it? Did you consider some other options like https://docs.rs/lmdb/latest/lmdb/, https://docs.rs/rocksdb/latest/rocksdb/ or https://docs.rs/leveldb/latest/leveldb/ ? And Reth is using its own wrapper https://github.com/paradigmxyz/reth/tree/main/crates/storage/libmdbx-rs with more free liscense.

The main (and only) reason at that time was Akula used that one.

I think it would be best to analyze other options before diving into the specifics (for example, I heard good things about `rocksdb`). The choice is still open.

Now that Akula is deprecated, it would make sense to explore more what Reth is using (should be similar). If one of the goals is to have tighter integration of bundler into execution client (which would have several advantages, such as faster reads and insights into Ethereum world state, shorter/direct calls to execution client functions instead of RPC API), it would be easier to use same DB type (or lib) as the execution client IMO.

**Comment by zsluedem** [comment]
https://github.com/ledgerwatch/erigon/wiki/Choice-of-storage-engine why erigon choose mdbx

**Comment by zsluedem** [comment]
@gakonst Hi. I am reviewing the database engine in reth now and I came into this comment you said in https://github.com/paradigmxyz/reth/pull/377#issuecomment-1345511060 that reth is going to switch into a pure rust db redb. I am wondering if you could share your plan about the timeline with me on this.

**Comment by gakonst** [comment]
No plan yet, we're open to using the best db for our needs. We'll benchmark first and then compare and then decide.

**Comment by zsluedem** [comment]
Done in https://github.com/Vid201/aa-bundler/pull/49
