### ISSUE TITLE
Modular ideas: split bundler, mempool and rpc into 3 crates.

### ISSUE THREAD

**Issue by zsluedem** [Vid201/aa-bundler#88]
Currently, we got everything in the `aa-bundler` crate.

Maybe we could separate these bundler, mempool and rpc into 3 crates and publish it for other rust developers to depend on. 

Generally I am talking to change Cargo.toml into 
```toml
[workspace]
members = [
    "bundler",
    "mempool",
    "rpc",
]
```

@Vid201 It is more like a discussion now and I am curious how you think about it.

Shortcoming:
A lot of code changes.

**Comment by zsluedem** [comment]
@Vid201 Another idea about implementing reusable modular components. This is related to https://github.com/Vid201/aa-bundler/issues/78#issuecomment-1478899310.

I think we should have an **orchestor** which manage the UoPool, Bundler. The idea is instead of having UoPool support multiple pool internally, we should keep UoPool simple and it should work with single pool and this orchestor could compose serveral UoPool and several Bundlers and even several rpc inside. IMO, putting several MemPool in one big UoPool struct doesn't provide flexible modular reusable crate.

**Comment by Vid201** [comment]
I think that's a great idea, it makes the bundler much more modular and easier to mess around with different components in other projects.

As we talked about, I think the best approach would be to start small, with first moving some pieces to `primitives` crate and then building out bundler, mempool, and rpc crates. We can also add some more if it makes sense.

**Comment by Vid201** [comment]
I think this project structure would make sense. What do you think @zsluedem ? Am I missing something?

**bin**
- bundler

**crates**
- contracts
- primitives
- bundler
- mempool
-- canonical (sanity checks and simulation for canonical mempool)
-- memory
-- database
- proto
- rpc

**Comment by zsluedem** [comment]
Looks good to me.
