### ISSUE TITLE
Updating reputation when UserOperation is valid

### ISSUE THREAD

**Issue by zsluedem** [Vid201/aa-bundler#93]
There are some undone todo in codes:

https://github.com/Vid201/aa-bundler/blob/ba51bad1dd76d17bbc60b9ddd1a5617f9b9dea59/src/uopool/services/uopool.rs#L120-L121

**Comment by zsluedem** [comment]
> Adding user operation to mempool will be done with PR #87 .

Not sure whether I understand it correctly. The pr is done and the work is already merged. Is that what you mean?

**Comment by zsluedem** [comment]
@Vid201 I am just curious whether `adding the user operation in mempool` is done.

**Comment by Vid201** [comment]
> @Vid201 I am just curious whether `adding the user operation in mempool` is done.

https://github.com/Vid201/aa-bundler/blob/main/src/uopool/services/uopool.rs#L127
